# filepath: Prueba2/client-pods/ubuntu-client-allowed.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-client-allowed
  namespace: mi-sistema # En el mismo namespace
  labels:
    client: allowed # Podríamos usar esta etiqueta en una NetworkPolicy más específica
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "250m"    # 0.25 CPU
        memory: "256Mi"  # 256 megabytes
      limits:
        cpu: "500m"    # 0.5 CPU
        memory: "512Mi"  # 512 megabytes