// filepath: Prueba2/client-pods/ubuntu-client-allowed.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-client-allowed
  namespace: mi-sistema # En el mismo namespace
  labels:
    client: allowed # Podríamos usar esta etiqueta en una NetworkPolicy más específica
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 10m    # 10 millicores (1% de un CPU)
        memory: 32Mi  # 32 megabytes
      limits:
        cpu: 50m    # 50 millicores (5% de un CPU)
        memory: 64Mi  # 64 megabytes