apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-books-data-pvc
  namespace: mi-sistema # En el mismo namespace que tu app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Solicita 1 GiB de almacenamiento
  storageClassName: "" # <--- AÑADE ESTA LÍNEA para enlazar a un PV estático
  volumeName: app-books-nfs-pv # <--- AÑADE ESTA LÍNEA para enlazar explícitamente a tu PV NFS