# filepath: ClustOps/deploys/app-books/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-books-service
  namespace: mi-sistema
  labels:
    app: app-books
spec:
  type: ClusterIP # Tipo de servicio, puede ser ClusterIP, NodePort, LoadBalancer, etc.
  # ClusterIP es el tipo por defecto y expone el servicio en una IP interna del clúster.
  # Si necesitas acceso externo, puedes cambiar a NodePort o LoadBalancer.
  selector:
    app: app-books
  ports:
  - protocol: TCP
    port: 5000       # Puerto interno del servicio en el clúster (puede ser el mismo que targetPort)
    targetPort: 5000 # Puerto en los pods (el containerPort de tu app Flask)
    # nodePort: 30005 # Opcional: especifica un NodePort o deja que Kubernetes elija