// filepath: Prueba2/network-policies/default-deny-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: mi-sistema
spec:
  podSelector: {} # Selecciona todos los pods en el namespace
  policyTypes:
  - Ingress # Aplica a tráfico entrante