# filepath: ClustOps/system/web-service/nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: mi-sistema
  labels:
    app: nginx
spec:
  type: NodePort 
  selector:
    app: nginx # Selecciona los pods con la etiqueta app:nginx
  ports:
  - protocol: TCP
    port: 80       # Puerto en el que el servicio está disponible DENTRO del clúster
    targetPort: 80 # Puerto en los pods al que se dirige el tráfico
    # nodePort: 30080 # Opcional: puedes especificar un NodePort o dejar que Kubernetes elija uno