# filepath: ClustOps/system/web-service/nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config # Asegúrate que el nombre y namespace coincidan
  namespace: mi-sistema
data:
  default.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        error_log /dev/stderr debug; # <--- AÑADE ESTO

        # Raíz de documentos estándar de Nginx
        root /usr/share/nginx/html;
        # Archivos índice estándar
        index index.html index.htm;

        # Location para la raíz. Debería servir el index.html por defecto de Nginx
        location / {
            try_files $uri $uri/ /index.html =404;
        }

          location /api/books/ {
              dav_methods off; # <--- AÑADE ESTA LÍNEA
              proxy_pass http://app-books-service.mi-sistema.svc.cluster.local:5000/books/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
 
 
          location = /books-ui {
              try_files /ui/books_ui.html =404; 
          }
         
          location = /nginx-hostname {
              default_type text/plain;
              return 200 "Servidor Nginx: $hostname\n"; 
          }
    } 