apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mi-sistema
  labels:
    app: nginx
spec:
  replicas: 3
  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # Etiqueta importante para el Service y NetworkPolicies
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # Modificaremos la página de inicio para mostrar el nombre del pod
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo \"<h1>Servido por: $POD_NAME</h1><p>Bienvenido a Nginx en Kubernetes!</p>\" > /usr/share/nginx/html/index.html"]
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts: # <--- SECCIÓN IMPORTANTE MODIFICADA/AÑADIDA
        - name: nginx-conf-volume # Para la configuración de Nginx (default.conf)
          mountPath: /etc/nginx/conf.d/default.conf # Ruta estándar donde Nginx carga configuraciones adicionales
          subPath: default.conf # La clave del ConfigMap 'nginx-config' que contiene tu default.conf
        - name: frontend-books-volume # Para la interfaz gráfica de libros
          mountPath: /usr/share/nginx/html/ui/books_ui.html # Ruta donde Nginx encontrará el books_ui.html
          subPath: books_ui.html # La clave del ConfigMap 'frontend-books-html'
      volumes: # <--- SECCIÓN IMPORTANTE MODIFICADA/AÑADIDA
      - name: nginx-conf-volume # Define el volumen para la configuración de Nginx
        configMap:
          name: nginx-config # Nombre del ConfigMap que contiene tu default.conf personalizado
          items: # Es buena práctica especificar los items para evitar conflictos si el ConfigMap tiene más claves
          - key: default.conf
            path: default.conf
      - name: frontend-books-volume # Define el volumen para la interfaz gráfica de libros
        configMap:
          name: frontend-books-html # Nombre del ConfigMap que contiene tu books_ui.html
          items:
          - key: books_ui.html
            path: books_ui.html